name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib=3.2.2
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - matplotlib-inline=0.1.2
  - ipympl=0.9.3
  - backtrader
  - ipython
  - yfinance
